apiVersion: v1
kind: Pod
metadata:
  name: training 
  labels:
     app: training
spec:
  containers:
    - name: "training"
      image: "topagentwilson/training:1.0.0"
      ports:
        -
          containerPort: 8099
          name: "http"
      resources:
        limits:
           cpu: "0.2"
           memory: "10Mi"

